export const ChangeableImages = ["/images/1.jpeg", "/images/2.png"];
export const ProductData = [
  {
    id: 17,
    img: "/images/a.jpg",
    name: "Bles Windbreaker Jacket (Model: Adi)",
    price: 199,
    discount: "-89%",
  },
  {
    id: 18,
    img: "/images/b.jpg",
    name: "Vintage T-9 Hair Trimmer For Men Battery Non...",
    price: 270,
    discount: "-73%",
  },
  {
    id: 19,
    img: "/images/c.jpg",
    name: "Wooden Saving Box Money Bank",
    price: 1199,
    discount: "-20%",
  },
  {
    id: 20,
    img: "/images/d.png",
    name: "Airpods Bluetooth Charging Case Pure...",
    price: 319,
    discount: "-68%",
  },
  {
    id: 21,
    img: "/images/e.jpg",
    name: "Unisex Holi Festival T-Shirt For Summer( Print May...",
    price: 189,
    discount: "-37%",
  },
  {
    id: 22,
    img: "/images/f.jpg",
    name: "Fabric Clothes Storage Organizer Basket Cubes...",
    price: "Rs.299",
    discount: "-76%",
  },
];

export const CategoryData = [
  { id: 1, name: "Breast Pump Accessories", image: "/images/i.jpg" },
  { id: 2, name: "Vinegar & Cooking Wine", image: "/images/ii.jpg" },
  { id: 3, name: "Other Projector Accessories", image: "/images/iii.jpg" },
  { id: 4, name: "Kids Bookcases & Shelving", image: "/images/iv.jpg" },
  { id: 5, name: "Canned", image: "/images/v.jpg" },
  { id: 6, name: "Toilet Paper", image: "//images/vi.jpg" },
  { id: 7, name: "Hoodies & Sweatshirts", image: "/images/vii.jpg" },
  { id: 8, name: "Bathroom Fittings", image: "/images/viii.jpg" },
  { id: 9, name: "Habitats & Accessories", image: "/images/ix.jpg" },
  { id: 10, name: "House Slippers", image: "/images/x.jpg" },
  { id: 11, name: "Christening", image: "image_url_11" },
  { id: 12, name: "Ergonomic Accessories", image: "image_url_12" },
  { id: 13, name: "Gimbals & Stabilizers", image: "image_url_13" },
  { id: 14, name: "Lotion, Cream and Scrubs", image: "image_url_14" },
  { id: 15, name: "Bathroom", image: "image_url_15" },
  { id: 16, name: "Still Water", image: "image_url_16" },
];

export const MoreProductData = [
  {
    title: "Product 1",
    price: "Rs.110",
    discount: "-11%",
    rating: 3.5,
    reviews: 15,
  },
  {
    title: "Product 2",
    price: "Rs.120",
    discount: "-12%",
    rating: 4.0,
    reviews: 20,
  },
  {
    title: "Product 3",
    price: "Rs.130",
    discount: "-13%",
    rating: 3.0,
    reviews: 25,
  },
  {
    title: "Product 4",
    price: "Rs.140",
    discount: "-14%",
    rating: 3.5,
    reviews: 30,
  },
  {
    title: "Product 5",
    price: "Rs.150",
    discount: "-15%",
    rating: 4.0,
    reviews: 35,
  },
  {
    title: "Product 6",
    price: "Rs.160",
    discount: "-16%",
    rating: 3.0,
    reviews: 40,
  },
  {
    title: "Product 7",
    price: "Rs.170",
    discount: "-17%",
    rating: 3.5,
    reviews: 45,
  },
  {
    title: "Product 8",
    price: "Rs.180",
    discount: "-18%",
    rating: 4.0,
    reviews: 50,
  },
  {
    title: "Product 9",
    price: "Rs.190",
    discount: "-19%",
    rating: 3.0,
    reviews: 55,
  },
  {
    title: "Product 10",
    price: "Rs.200",
    discount: "-20%",
    rating: 3.5,
    reviews: 60,
  },
  {
    title: "Product 11",
    price: "Rs.210",
    discount: "-21%",
    rating: 4.0,
    reviews: 65,
  },
  {
    title: "Product 12",
    price: "Rs.220",
    discount: "-22%",
    rating: 3.0,
    reviews: 70,
  },
  {
    title: "Product 13",
    price: "Rs.230",
    discount: "-23%",
    rating: 3.5,
    reviews: 75,
  },
  {
    title: "Product 14",
    price: "Rs.240",
    discount: "-24%",
    rating: 4.0,
    reviews: 80,
  },
  {
    title: "Product 15",
    price: "Rs.250",
    discount: "-25%",
    rating: 3.0,
    reviews: 85,
  },
  {
    title: "Product 16",
    price: "Rs.260",
    discount: "-26%",
    rating: 3.5,
    reviews: 90,
  },
  {
    title: "Product 17",
    price: "Rs.270",
    discount: "-27%",
    rating: 4.0,
    reviews: 95,
  },
  {
    title: "Product 18",
    price: "Rs.280",
    discount: "-28%",
    rating: 3.0,
    reviews: 100,
  },
  {
    title: "Product 19",
    price: "Rs.290",
    discount: "-29%",
    rating: 3.5,
    reviews: 105,
  },
  {
    title: "Product 20",
    price: "Rs.300",
    discount: "-30%",
    rating: 4.0,
    reviews: 110,
  },
  {
    title: "Product 21",
    price: "Rs.310",
    discount: "-31%",
    rating: 3.0,
    reviews: 115,
  },
  {
    title: "Product 22",
    price: "Rs.320",
    discount: "-32%",
    rating: 3.5,
    reviews: 120,
  },
  {
    title: "Product 23",
    price: "Rs.330",
    discount: "-33%",
    rating: 4.0,
    reviews: 125,
  },
  {
    title: "Product 24",
    price: "Rs.340",
    discount: "-34%",
    rating: 3.0,
    reviews: 130,
  },
  {
    title: "Product 25",
    price: "Rs.350",
    discount: "-35%",
    rating: 3.5,
    reviews: 135,
  },
  {
    title: "Product 26",
    price: "Rs.360",
    discount: "-36%",
    rating: 4.0,
    reviews: 140,
  },
  {
    title: "Product 27",
    price: "Rs.370",
    discount: "-37%",
    rating: 3.0,
    reviews: 145,
  },
  {
    title: "Product 28",
    price: "Rs.380",
    discount: "-38%",
    rating: 3.5,
    reviews: 150,
  },
  {
    title: "Product 29",
    price: "Rs.390",
    discount: "-39%",
    rating: 4.0,
    reviews: 155,
  },
  {
    title: "Product 30",
    price: "Rs.400",
    discount: "-40%",
    rating: 3.0,
    reviews: 160,
  },
  {
    title: "Product 31",
    price: "Rs.410",
    discount: "-41%",
    rating: 3.5,
    reviews: 165,
  },
  {
    title: "Product 32",
    price: "Rs.420",
    discount: "-42%",
    rating: 4.0,
    reviews: 170,
  },
  {
    title: "Product 33",
    price: "Rs.430",
    discount: "-43%",
    rating: 3.0,
    reviews: 175,
  },
  {
    title: "Product 34",
    price: "Rs.440",
    discount: "-44%",
    rating: 3.5,
    reviews: 180,
  },
  {
    title: "Product 35",
    price: "Rs.450",
    discount: "-45%",
    rating: 4.0,
    reviews: 185,
  },
  {
    title: "Product 36",
    price: "Rs.460",
    discount: "-46%",
    rating: 3.0,
    reviews: 190,
  },
  {
    title: "Product 37",
    price: "Rs.470",
    discount: "-47%",
    rating: 3.5,
    reviews: 195,
  },
  {
    title: "Product 38",
    price: "Rs.480",
    discount: "-48%",
    rating: 4.0,
    reviews: 200,
  },
  {
    title: "Product 39",
    price: "Rs.490",
    discount: "-49%",
    rating: 3.0,
    reviews: 205,
  },
  {
    title: "Product 40",
    price: "Rs.500",
    discount: "-50%",
    rating: 3.5,
    reviews: 210,
  },
  {
    title: "Product 41",
    price: "Rs.510",
    discount: "-51%",
    rating: 4.0,
    reviews: 215,
  },
  {
    title: "Product 42",
    price: "Rs.520",
    discount: "-52%",
    rating: 3.0,
    reviews: 220,
  },
  {
    title: "Product 43",
    price: "Rs.530",
    discount: "-53%",
    rating: 3.5,
    reviews: 225,
  },
  {
    title: "Product 44",
    price: "Rs.540",
    discount: "-54%",
    rating: 4.0,
    reviews: 230,
  },
  {
    title: "Product 45",
    price: "Rs.550",
    discount: "-55%",
    rating: 3.0,
    reviews: 235,
  },
  {
    title: "Product 46",
    price: "Rs.560",
    discount: "-56%",
    rating: 3.5,
    reviews: 240,
  },
  {
    title: "Product 47",
    price: "Rs.570",
    discount: "-57%",
    rating: 4.0,
    reviews: 245,
  },
  {
    title: "Product 48",
    price: "Rs.580",
    discount: "-58%",
    rating: 3.0,
    reviews: 250,
  },
  {
    title: "Product 49",
    price: "Rs.590",
    discount: "-59%",
    rating: 3.5,
    reviews: 255,
  },
  {
    title: "Product 50",
    price: "Rs.600",
    discount: "-10%",
    rating: 4.0,
    reviews: 260,
  },
];

export const Link1 = [
  { title: "Help Center", link: "/" },
  { title: "How to buy", link: "/" },
  { title: "Returns & Refunds", link: "/" },
  { title: "Contact Us", link: "/" },
];

export const Link2 = [
  { title: "About Daraz", link: "/" },
  { title: "Careers", link: "/" },
  { title: "Daraz Blog", link: "/" },
  { title: "Terms & Conditions", link: "/" },
  { title: "Privacy Policy", link: "/" },
  { title: "Digital Payments", link: "/" },
  { title: "Daraz Customer University", link: "/" },
  { title: "Review and Win", link: "/" },
  { title: "Meet the winners", link: "/" },
  { title: "Daraz University", link: "/" },
  { title: "Sell on Daraz", link: "/" },
  { title: "Code of Conduct", link: "/" },
];
export const ProductDescriptionData = [
  {
    id: 1,
    product_name: "Breast Pump Accessories",
    category: "Health & Baby Care",
    brand: "No Brand",
    price: { current: 99, original: 199, discount: "-50%" },
    rating: "No Ratings",
    color: "White",
    promotions: "No Min Spend",
    quantity: 1,
    image: "/images/i.jpg",
  },
  {
    id: 2,
    product_name: "Vinegar & Cooking Wine",
    category: "Grocery",
    brand: "No Brand",
    price: { current: 150, original: 300, discount: "-50%" },
    rating: "4.5",
    color: "N/A",
    promotions: "Free Shipping",
    quantity: 1,
    image: "/images/ii.jpg",
  },
  {
    id: 3,
    product_name: "Other Projector Accessories",
    category: "Electronics",
    brand: "No Brand",
    price: { current: 299, original: 599, discount: "-50%" },
    rating: "3.8",
    color: "Black",
    promotions: "Limited Offer",
    quantity: 1,
    image: "/images/iii.jpg",
  },
  {
    id: 4,
    product_name: "Kids Bookcases & Shelving",
    category: "Furniture",
    brand: "No Brand",
    price: { current: 499, original: 999, discount: "-50%" },
    rating: "4.0",
    color: "Multicolor",
    promotions: "Discounted Price",
    quantity: 1,
    image: "/images/iv.jpg",
  },
  {
    id: 5,
    product_name: "Canned Food",
    category: "Grocery",
    brand: "No Brand",
    price: { current: 75, original: 150, discount: "-50%" },
    rating: "4.2",
    color: "N/A",
    promotions: "Buy 1 Get 1 Free",
    quantity: 1,
    image: "/images/v.jpg",
  },
  {
    id: 6,
    product_name: "Toilet Paper",
    category: "Household Essentials",
    brand: "No Brand",
    price: { current: 120, original: 240, discount: "-50%" },
    rating: "4.7",
    color: "White",
    promotions: "Bulk Discount",
    quantity: 1,
    image: "/images/vi.jpg",
  },
  {
    id: 7,
    product_name: "Hoodies & Sweatshirts",
    category: "Clothing",
    brand: "No Brand",
    price: { current: 799, original: 1599, discount: "-50%" },
    rating: "4.5",
    color: "Gray",
    promotions: "Limited Offer",
    quantity: 1,
    image: "/images/vii.jpg",
  },
  {
    id: 8,
    product_name: "Bathroom Fittings",
    category: "Home Improvement",
    brand: "No Brand",
    price: { current: 599, original: 1199, discount: "-50%" },
    rating: "4.3",
    color: "Silver",
    promotions: "Limited Stock",
    quantity: 1,
    image: "/images/viii.jpg",
  },
  {
    id: 9,
    product_name: "Habitats & Accessories",
    category: "Pets",
    brand: "No Brand",
    price: { current: 199, original: 399, discount: "-50%" },
    rating: "4.1",
    color: "Green",
    promotions: "Discounted Price",
    quantity: 1,
    image: "/images/ix.jpg",
  },
  {
    id: 10,
    product_name: "House Slippers",
    category: "Footwear",
    brand: "No Brand",
    price: { current: 349, original: 699, discount: "-50%" },
    rating: "4.6",
    color: "Blue",
    promotions: "Limited Offer",
    quantity: 1,
    image: "/images/x.jpg",
  },
  {
    id: 11,
    product_name: "Christening Dress",
    category: "Clothing",
    brand: "No Brand",
    price: { current: 899, original: 1799, discount: "-50%" },
    rating: "4.8",
    color: "White",
    promotions: "Free Shipping",
    quantity: 1,
    image: "image_url_11",
  },
  {
    id: 12,
    product_name: "Ergonomic Accessories",
    category: "Office & Supplies",
    brand: "No Brand",
    price: { current: 250, original: 500, discount: "-50%" },
    rating: "4.4",
    color: "Black",
    promotions: "Buy More, Save More",
    quantity: 1,
    image: "image_url_12",
  },
  {
    id: 13,
    product_name: "Gimbals & Stabilizers",
    category: "Electronics",
    brand: "No Brand",
    price: { current: 2599, original: 5199, discount: "-50%" },
    rating: "4.5",
    color: "Black",
    promotions: "Discounted Price",
    quantity: 1,
    image: "image_url_13",
  },
  {
    id: 14,
    product_name: "Lotion, Cream and Scrubs",
    category: "Beauty & Personal Care",
    brand: "No Brand",
    price: { current: 299, original: 599, discount: "-50%" },
    rating: "4.3",
    color: "N/A",
    promotions: "Buy 2 Get 1 Free",
    quantity: 1,
    image: "image_url_14",
  },
  {
    id: 15,
    product_name: "Bathroom Essentials",
    category: "Home Improvement",
    brand: "No Brand",
    price: { current: 450, original: 900, discount: "-50%" },
    rating: "4.0",
    color: "White",
    promotions: "Limited Stock",
    quantity: 1,
    image: "image_url_15",
  },
  {
    id: 16,
    product_name: "Still Water Bottle",
    category: "Beverages",
    brand: "No Brand",
    price: { current: 50, original: 100, discount: "-50%" },
    rating: "4.2",
    color: "Transparent",
    promotions: "Free Shipping",
    quantity: 1,
    image: "image_url_16",
  },
  {
    id: 17,
    product_name: "Bles Windbreaker Jacket (Model: Adi)",
    category: "Clothing",
    brand: "No Brand",
    price: { current: 199, original: 1799, discount: "-89%" },
    rating: "4.2",
    color: "Black",
    promotions: "Limited Offer",
    quantity: 1,
    image: "/images/a.jpg",
  },
  {
    id: 18,
    product_name: "Vintage T-9 Hair Trimmer For Men",
    category: "Personal Care",
    brand: "No Brand",
    price: { current: 270, original: 999, discount: "-73%" },
    rating: "4.5",
    color: "Gold",
    promotions: "Free Shipping",
    quantity: 1,
    image: "/images/b.jpg",
  },
  {
    id: 19,
    product_name: "Wooden Saving Box Money Bank",
    category: "Home & Living",
    brand: "No Brand",
    price: { current: 1199, original: 1499, discount: "-20%" },
    rating: "4.3",
    color: "Brown",
    promotions: "Discounted Price",
    quantity: 1,
    image: "/images/c.jpg",
  },
  {
    id: 20,
    product_name: "AirPods Bluetooth Charging Case",
    category: "Electronics",
    brand: "No Brand",
    price: { current: 319, original: 999, discount: "-68%" },
    rating: "4.0",
    color: "White",
    promotions: "Limited Stock",
    quantity: 1,
    image: "/images/d.png",
  },
  {
    id: 21,
    product_name: "Unisex Holi Festival T-Shirt",
    category: "Clothing",
    brand: "No Brand",
    price: { current: 189, original: 299, discount: "-37%" },
    rating: "4.1",
    color: "Multicolor",
    promotions: "Special Festival Offer",
    quantity: 1,
    image: "/images/e.jpg",
  },
  {
    id: 22,
    product_name: "Fabric Clothes Storage Organizer Basket Cubes",
    category: "Home & Living",
    brand: "No Brand",
    price: { current: 299, original: 1249, discount: "-76%" },
    rating: "4.6",
    color: "Gray",
    promotions: "Bulk Discount",
    quantity: 1,
    image: "/images/f.jpg",
  },
];
